export {Noticias} from './Noticias' 
export {Perfil} from './Perfil' 
export {Checkins} from './Checkins' 
export {Times} from './Times' 
export {Cronograma} from './Cronograma' 
export {Reservas} from './Reservas'
