export {Noticias} from './Noticias' 
export {Perfil} from './Perfil' 
export {Checkins} from './Checkins' 
export {Times} from './Times' 
export {Reservas} from './Reservas'
export {Testes} from './Testes'
export {Inicio} from './Inicio'
export { Cronograma2 } from './Cronograma2'
//export {Register}from'./Register'